### ISSUE TITLE
Неправильні тести пропозицій

### ISSUE THREAD

**Issue by yarsanich** [openprocurement/openprocurement.tender.competitivedialogue#131]
В тестах пропозицій stage 1, неправильний тест. На разі, тестується Європейська процедура, а не процуедура конкурентного діалогу. **(Створюєтсья тендер) tender['procurementMethodType] = 'aboveThresholdEU'.**  У тест кейсах bid.py.

Відповідно до цього, даний тест не коректний.
https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/production/openprocurement/tender/competitivedialogue/tests/stage1/bid.py#L890

Якщо в plugins до api не підключати aboveThresholdEU, то тести не пройдуть. 

https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/production/openprocurement/tender/competitivedialogue/tests/tests.ini#L15

**Comment by itvan** [comment]
@vmaksymiv прохання закрити це issue. На майбутнє, будемо вказувати в Pull Request кодові слова для автоматичного закриття.
