### ISSUE TITLE
Поправити сумісність коду конкурентного діалогу з не сумісний з dev гілкою op.api і з master гілками openua та openeu 

### ISSUE THREAD

**Issue by kroman0** [openprocurement/openprocurement.tender.competitivedialogue#59]
Зараз код конкурентного діалогу не сумісний з dev гілкою op.api і з master гілками openua та openeu що не дозволяє оновити dev пісочницю.

**Comment by gorserg** [comment]
Наразі коректна робота КД (повноцінне проходження обох етапів) можлива лише на бранчі extend_acl_for_cd (для op.api), а так як це була на той момент production гілка, то і openeu, openua також було підключено явно з production гілок (https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/production/buildout.cfg#L11 - щоб успішно travis проходив). Формально для сумісності переключимо на master гілки, але процедура не буде повноцінною без тих змін.

**Comment by kroman0** [comment]
dev гілка op.api включає extend_acl_for_cd

**Comment by gorserg** [comment]
Пул https://github.com/openprocurement/openprocurement.tender.competitivedialogue/pull/63 
Але бажано для початку потрібно змерджити master в production, там зараз  застаріла гілка (This branch is 9 commits behind master)

**Comment by kroman0** [comment]
https://github.com/openprocurement/openprocurement.tender.competitivedialogue/pull/64
