### ISSUE TITLE
Correct configuration of package dependencies

### ISSUE THREAD

**Issue by vmaksymiv** [openprocurement/openprocurement.tender.competitivedialogue#75]
Потрібно винести все "зайве" з requires і залишити там тільки setuptools.
Приклад конфігурації залежностей можна підглянути в [openprocurement.contracting.api](https://github.com/openprocurement/openprocurement.contracting.api/blob/deps_optimizations/setup.py)

Це потрібно щоб мати можливість зібрати міст окремо від api аплікації і не тягнути нічого зайвого.

**Comment by Krokop** [comment]
Issues ще актуальне?
