### ISSUE TITLE
На другому етапі мультилотової закупівлі конкурентного діалогу з публікацією англ. мовою (competitiveDialogueEU), у кваліфікації ЦБД дублює пропозиції

### ISSUE THREAD

**Issue by ktarasz** [openprocurement/openprocurement.tender.competitivedialogue#93]
Доброго дня.
На другому етапі мультилотової закупівлі конкурентного діалогу з публікацією англ. мовою (competitiveDialogueEU), у кваліфікації ЦБД дублює пропозиції
https://lb.api-sandbox.openprocurement.org/api/2.3/tenders/09ecd1e222e840e08ec77879ec2b0216
UA-2016-10-12-000094-1.2

Було створено мультилотовую закупівлю з двома лотами, та подано по кожному лоту по три пропозиції як на першому етапі, так і на другому.
для аналізу потрібні логи по змінах тендеру на сервері - можемо щось зробити, аби з'ясувати, як це у майданчика виходить? бо такої поведінки не було в жодного іншного

Ось change повязаний із qualifications

```
-   author: chronograph
    changes:
    -   op: add
        path: /lots/1/auctionPeriod/shouldStartAfter
        value: '2016-10-13T11:47:30+03:00'
    -   op: add
        path: /lots/0/auctionPeriod/shouldStartAfter
        value: '2016-10-13T11:47:30+03:00'
    -   op: remove
        path: /qualificationPeriod
    -   op: replace
        path: /status
        value: active.tendering
    -   op: remove
        path: /qualifications
    -   op: add
        path: /next_check
        value: '2016-10-13T11:30:00+03:00'
    -   op: replace
        path: /date
        value: '2016-10-13T10:58:03.015997+03:00'
    date: '2016-10-13T11:31:11.695341+03:00'
    rev: 11-3a84b020b9fe47b3f38c0308776c001d
```

11-3a84b020b9fe47b3f38c0308776c001d - принесла усі qualifications

**Comment by ktarasz** [comment]
Уточніть яку інформацію вам надати (Структуру тендера, логи)

**Comment by Krokop** [comment]
Нам потрібен json тендера та логи з сервера апі
(journalctl TENDER_ID=09ecd1e222e840e08ec77879ec2b0216)

**Comment by ktarasz** [comment]
Ось в чому проблема... Пропозиція 58cfa8abe57745a1b1294d9669ce6828 має lotValues із дубляжем relatedLot: 2ceb288b9b9a4759b05f160032205b3b. 

```
-   date: '2016-10-13T11:03:23.391760+03:00'
    id: 58cfa8abe57745a1b1294d9669ce6828
    lotValues:
    -   date: '2016-10-13T11:03:23.392140+03:00'
        relatedLot: 2ceb288b9b9a4759b05f160032205b3b
         ...
    -   date: '2016-10-13T11:03:23.392452+03:00'
        relatedLot: **2ceb288b9b9a4759b05f160032205b3b**
        ...
    -   date: '2016-10-13T11:03:23.392750+03:00'
        relatedLot: _cedd55d99b7b4bd2b83c4bf0ad9dc240_
        ...
    -   date: '2016-10-13T11:03:23.393039+03:00'
        relatedLot: _cedd55d99b7b4bd2b83c4bf0ad9dc240_
        ...
    owner: public-bid.com.ua
```
Я спробую дослідити чи такий хак проходить із іншими процедурами, якщо так то зміни мають йти в openprocurement.api
