### ISSUE TITLE
procurementMethod "selective" для тендерів другої стадії

### ISSUE THREAD

**Issue by vmaksymiv** [openprocurement/openprocurement.tender.competitivedialogue#96]
Тендери другого етапу competitiveDialogueEU.stage2 та competitiveDialogueUA.stage2 повинні бути selective типу ("procurementMethod": "selective").

**Comment by Krokop** [comment]
@vmaksymiv На пісочниці є приклад де на другого етапі  procurementMethod не selective?

**Comment by vmaksymiv** [comment]
Перепрошую, недодивився.
